### ISSUE TITLE
can't able to install types from npm

### ISSUE THREAD

**Issue by jeetrabadiya** [Leocardoso94/animated-number-react#17]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fanimated-number-react - Not found
npm ERR! 404 
npm ERR! 404  '@types/animated-number-react@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Leocardoso94** [comment]
Hi @jeetrabadiya this package doesn't have types

**Comment by jeetrabadiya** [comment]
@Leocardoso94 so how we can use in react-typescript?

**Comment by jeetrabadiya** [comment]
@Leocardoso94 No problem... I have created custom d.ts file for this packages. Maybe it will help to those people who want to use this package in react-typescript.

**Comment by magikadev** [comment]
@Leocardoso94  can you please add types for this package? I really want to use this in typescript.

**Comment by jeetrabadiya** [comment]
@magic990619 I have a solution for types issue. Please refer this comment it will work for typescript.

https://github.com/Leocardoso94/animated-number-react/issues/17#issuecomment-700710670
