### ISSUE TITLE
How can i add custom styles?

### ISSUE THREAD

**Issue by jose920405** [Leocardoso94/animated-number-react#9]
The only way is updated all `span` tag. But that affects my others span in the proyect.

Should i add styles to span with a selector? or there is cleaner way?

**Comment by Doylito** [comment]
@jose920405 Did you have any luck with this? I am having the same issue.

**Comment by Leocardoso94** [comment]
I add an option to pass a className to the span aba9fd7019431cd437aa96580ed7b9c73cc5b259

**Comment by Leocardoso94** [comment]
update to 0.1.0
